-- SQL to create the gas prices table in Supabase
-- Run this in the SQL Editor of your Supabase dashboard

CREATE TABLE IF NOT EXISTS public.prices (
    id bigint generated by default as identity primary key,
    station_name text not null,
    address text,
    municipality text,
    zone text,
    price_95 numeric(10,3),
    price_diesel numeric(10,3),
    created_at timestamptz default now(),
    is_cheapest_asturias_95 boolean default false,
    is_cheapest_asturias_diesel boolean default false
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_prices_zone ON public.prices(zone);
CREATE INDEX IF NOT EXISTS idx_prices_created_at ON public.prices(created_at DESC);
