name: Daily Gas Price Update

on:
  schedule:
        - cron: '10 6 * * *' # 08:10 AM Madrid (CEST)
  workflow_dispatch: # Permite ejecutarlo a mano

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scraper.js
